### ISSUE TITLE
Error when trying to show multiple channels

### ISSUE THREAD

**Issue by JonasCF** [abrazhe/image-funcut#23] opened 2015-11-04 13:31 UTC
press on show timeseries give this error:
   File "c:\Anaconda\Scripts\funcut.py", line 536, in _show_all_timeseries_btn_fi
red
    self.parent.picker.show_zview()
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1570, in show_zview
    for lx in l.legendHandles:
AttributeError: 'NoneType' object has no attribute 'legendHandles'
in show_all_timeseries_btn_fired
in Picker.show_zview()
area <itertools._grouper object at 0x0000000020928390>
[u'r']
Exception occurred in traits notification handler for object: <__main__.FrameSeq
uenceOpts object at 0x000000001BDCCDB0>, trait: show_all_timeseries_btn, old val
ue: <undefined>, new value: 0
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\traits\trait_notifiers.py", line 340, in _
_call__
    self.handler( *args )
  File "c:\Anaconda\Scripts\funcut.py", line 536, in _show_all_timeseries_btn_fi
red
    self.parent.picker.show_zview()
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1570, in show_zview
    for lx in l.legendHandles:
AttributeError: 'NoneType' object has no attribute 'legendHandles'
in show_all_timeseries_btn_fired
in Picker.show_zview()
area <itertools._grouper object at 0x00000000666B25F8>
[u'r']
Exception occurred in traits notification handler for object: <__main__.FrameSeq
uenceOpts object at 0x000000001BDCCDB0>, trait: show_all_timeseries_btn, old val
ue: <undefined>, new value: 0
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\traits\trait_notifiers.py", line 340, in _
_call__
    self.handler( *args )
  File "c:\Anaconda\Scripts\funcut.py", line 536, in _show_all_timeseries_btn_fi
red
    self.parent.picker.show_zview()
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1570, in show_zview
    for lx in l.legendHandles:
AttributeError: 'NoneType' object has no attribute 'legendHandles'
in show_all_timeseries_btn_fired
in Picker.show_zview()
area <itertools._grouper object at 0x0000000086A4D8D0>
[u'r']
Exception occurred in traits notification handler for object: <__main__.FrameSeq
uenceOpts object at 0x000000001BDCCDB0>, trait: show_all_timeseries_btn, old val
ue: <undefined>, new value: 0
Traceback (most recent call last):
  File "c:\Anaconda\lib\site-packages\traits\trait_notifiers.py", line 340, in _
_call__
    self.handler( *args )
  File "c:\Anaconda\Scripts\funcut.py", line 536, in _show_all_timeseries_btn_fi
red
    self.parent.picker.show_zview()
  File "c:\Anaconda\lib\site-packages\imfun\ui.py", line 1570, in show_zview
    for lx in l.legendHandles:
AttributeError: 'NoneType' object has no attribute 'legendHandles'

**Comment by abrazhe** [comment] 2015-11-04 14:46
OK, I'll try to figure out what happens tomorrow

**Comment by abrazhe** [comment] 2015-11-04 14:56
I can't reproduce with the current version. Did you update recently? If you run a notebook or ipython console, what is the output of:
```python
import imfun
imfun.__version__
```
?

**Comment by abrazhe** [comment] 2015-11-04 15:23
Should be fixed by https://github.com/abrazhe/image-funcut/commit/c0b85bf62b6a9862c7ce56c6504c3c398031982c

**Closed by abrazhe** 2015-11-04 15:23 UTC
